title: Brandon Azbill's Blog
description: > # this means to ignore newlines until "baseurl:"
  Check out my blog!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "bazbill115.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Brandon Azbill # add your name
author-img: brandon-azbill.png # add your photo
about-author: B.S. Computer Science |
  UVA 2021  |
  CKA/CKAD Certifications # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: bazbill115 # add your Github handle
social-linkedin: brandonazbill
social-email: bazbill115@gmail.com

# Disqus
discus-identifier: bazbill115 # add your discus identifier

# Tracker
analytics: bazbill115

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
